# pandas

In [37]:
import pandas as pd

In [38]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [40]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [41]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [42]:
mix = pd.DataFrame({"Population" : population , "Area":area})
mix

Population    Area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [43]:
mix["density"] = mix['Population'] / mix["Area"]
mix

Population    Area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [44]:
mix.T

California         Texas      New York       Florida  \
Population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
Area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
Population  1.288214e+07  
Area        1.499950e+05  
density     8.588376e+01

In [45]:
mix.iloc[:3, :2]

Population    Area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [46]:
mix.loc[:'Illinois', :'Population']

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

# numpy

In [47]:
import numpy as np

In [82]:
m1 = np.random.randint(10, size=7) 
m2 = np.random.randint(10, size=(3, 3)) 
m3 = np.random.randint(10, size=(3, 6, 4))

In [83]:
m1

array([5, 8, 1, 3, 1, 3, 9])

In [84]:
m2

array([[4, 0, 6],
       [8, 5, 7],
       [3, 3, 3]])

In [85]:
m3

array([[[3, 2, 4, 7],
        [7, 6, 1, 8],
        [7, 9, 8, 8],
        [3, 4, 3, 2],
        [9, 7, 3, 4],
        [7, 8, 9, 7]],

       [[3, 6, 7, 7],
        [2, 5, 7, 5],
        [9, 7, 0, 1],
        [3, 6, 3, 5],
        [3, 5, 4, 0],
        [5, 1, 7, 1]],

       [[8, 1, 7, 6],
        [8, 7, 8, 8],
        [0, 5, 7, 3],
        [4, 6, 8, 7],
        [8, 1, 5, 1],
        [7, 4, 7, 0]]])

In [86]:
m2[0,0] = 2

In [87]:
m2

array([[2, 0, 6],
       [8, 5, 7],
       [3, 3, 3]])

In [88]:
m_test = np.arange(10)
m_test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
m_test[:3]

array([0, 1, 2])

In [90]:
m_test[6:]

array([6, 7, 8, 9])

In [91]:
m_test[3:8]

array([3, 4, 5, 6, 7])

In [92]:
m_test[::2]

array([0, 2, 4, 6, 8])

In [93]:
m_test[1::2]

array([1, 3, 5, 7, 9])

In [94]:
m_test[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [95]:
m2[:: , ::2]

array([[2, 6],
       [8, 7],
       [3, 3]])

In [96]:
x2[:2, :3]

array([[3, 0, 5],
       [5, 4, 8]])

In [102]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.array([7,8,9])

np.concatenate([x1 ,x2,x3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
u = np.vstack([x1,x2])
u

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.hstack([x1,x3])

array([1, 2, 3, 7, 8, 9])

In [112]:
upper , lower = np.vsplit(u,[2])
print(upper)
print(lower)

[[1 2 3]
 [4 5 6]]
[]


In [113]:
left , right = np.hsplit(u,[2])
print(left)
print(right)

[[1 2]
 [4 5]]
[[3]
 [6]]


In [114]:
np.sort(m2)

array([[0, 2, 6],
       [5, 7, 8],
       [3, 3, 3]])

In [115]:
np.sort(m2 , axis=0)

array([[2, 0, 3],
       [3, 3, 6],
       [8, 5, 7]])

In [116]:
np.sort(m2 , axis=1)

array([[0, 2, 6],
       [5, 7, 8],
       [3, 3, 3]])